In [212]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [213]:
data = pd.read_csv(r"C:\Users\DELL\Downloads\micka_sell_dataset_06-07-2025 (1).csv")
data.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_11432\1129046821.py:1: DtypeWarning: Columns (264) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r"C:\Users\DELL\Downloads\micka_sell_dataset_06-07-2025 (1).csv")

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,False,False,True,False,False,False,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,False,False,False,False,False,False,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,False,False,False,True,False,False,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,False,False,False,False,False,False,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,False,False,False,False,False,False,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

CHECKING MISSING DATA

In [214]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3993 entries, 0 to 3992
Columns: 353 entries, ABOVE_1H_NEGATIVE to outcome_02
dtypes: bool(69), float64(65), int64(126), object(93)
memory usage: 8.9+ MB

In [215]:
dataset = data.isna().sum()
print(dataset.to_string(index=True))

ABOVE_1H_NEGATIVE                   0
ABOVE_1H_POSITIVE                   0
BELOW                               0
BELOW_1H                            0
BELOW_1H_BIG                        0
BELOW_1H_GO                         0
BELOW_1H_STAMP                      0
BUY_H                               0
EXTREME_ABOVE                       0
EXTREME_BELOW                       0
FAILED_PURCHASED                    0
INDICATOR_1                         0
INDICATOR_10                        0
INDICATOR_11                        0
INDICATOR_2                         0
INDICATOR_20                        0
INDICATOR_21                        0
INDICATOR_22                        0
INDICATOR_23                        0
INDICATOR_24                        0
INDICATOR_3                         0
INDICATOR_4                         0
INDICATOR_5                         0
INDICATOR_6                         0
INDICATOR_7                         0
INDICATOR_8                         0
INDICATOR_9                         0
JUST_CROSS_ABOVE                    0
MACD_1H                             0
MACD_1H_BELOW_AVG                   0
MACD_1H_BELOW_MIN                   0
MACD_1H_SIGNAL_LINE                 0
MACD_1H_UP                          0
MACD_DAY_CURVED                     0
MACD_DAY_MIXED                      0
MACD_DAY_NEGATIVE                   0
MACD_DAY_NEGATIVE_EXTREME           0
MACD_DAY_POSITIVE                   0
MACD_DAY_POSITIVE_BY_2              0
MACD_DAY_POSITIVE_EXTREME           0
MACD_M_1                            0
MACD_M_1_BELOW_AVG                  0
MACD_M_1_BELOW_MIN                  0
MACD_M_5                            0
MACD_M_5_BELOW_AVG                  0
MACD_M_5_BELOW_MIN                  0
MACD_SIGNAL_LINE_M_1                0
MACD_SIGNAL_LINE_M_5                0
M_0                                 0
M_1                                 0
M_10                                0
M_100                               0
M_101                               0
M_102                               0
M_103                               0
M_104                               0
M_105                               0
M_106                               0
M_107                               0
M_108                               0
M_109                               0
M_11                                0
M_110                               0
M_111                               0
M_112                               0
M_113                               0
M_114                               0
M_115                               0
M_116                               0
M_117                               0
M_118                               0
M_119                               0
M_12                                0
M_120                               0
M_13                                0
M_14                                0
M_15                                0
M_16                                0
M_17                                0
M_18                                0
M_19                                0
M_2                                 0
M_20                                0
M_21                                0
M_22                                0
M_23                                0
M_24                                0
M_25                                0
M_26                                0
M_27                                0
M_28                                0
M_29                                0
M_3                                 0
M_30                                0
M_31                                0
M_32                                0
M_33                                0
M_34                                0
M_35                                0
M_36                                0
M_37                                0
M_38                                0
M_39                                0
M_4                                 0
M_40                                0
M_41                                0
M_42                                0
M_43                                0
M_44                                0
M_45                                0
M_46                                0
M_47                                0
M_48                                0
M_49                                0
M_5                                 0
M_50                                0
M_51                                0
M_52                                0
M_53                                0
M_54                                0
M_55                                0
M_56                                0
M_57                                0
M_58                                0
M_59                                0
M_6                                 0
M_60                                0
M_61                                0
M_62                                0
M_63                                0
M_64                                0
M_65                                0
M_66                                0
M_67                                0
M_68                                0
M_69                                0
M_7                                 0
M_70                                0
M_71                                0
M_72                                0
M_73                                0
M_74                                0
M_75                                0
M_76                                0
M_77                                0
M_78                                0
M_79                                0
M_8                                 0
M_80                                0
M_81                                0
M_82                                0
M_83                                0
M_84                                0
M_85                                0
M_86                                0
M_87                                0
M_88                                0
M_89                                0
M_9                                 0
M_90                                0
M_91                                0
M_92                                0
M_93                                0
M_94                                0
M_95                                0
M_96                                0
M_97                                0
M_98                                0
M_99                                0
ROC_9D                              0
ROC_9D_H                            0
ROC_9D_H_BELOW_AVG                  0
ROC_9D_H_BELOW_MIN                  0
ROC_9D_M                            0
ROC_9D_M_1                          0
ROC_9D_M_1_BELOW_AVG                0
ROC_9D_M_1_BELOW_MIN                0
ROC_9D_M_BELOW_AVG                  0
ROC_9D_M_BELOW_MIN                  0
ROC_AVG_30D_1MIN                    0
ROC_AVG_30D_5MIN                    0
ROC_CURVED                          0
ROC_CURVED_DAY                      0
ROC_CURVED_DAY_NEGATIVE             0
ROC_CURVED_DAY_POSITIVE             0
ROC_CURVED_HOUR_NEGATIVE            0
ROC_CURVED_HOUR_POSITIVE            0
ROC_CURVED_NOW                      0
ROC_H                               0
RSI_AVG_30D_1MIN                    0
RSI_AVG_30D_5MIN                    0
RSI_CURVED                          0
RSI_CURVED_H                        0
RSI_DOWN                            0
RSI_DOWN_H                          0
RSI_H                               0
RSI_NOW                             0
RSI_NOW_H                           0
RSI_NOW_H_BELOW_AVG                 0
RSI_NOW_H_BELOW_MIN                 0
RSI_NOW_M                           0
RSI_NOW_M_1                         0
RSI_NOW_M_1_BELOW_AVG               0
RSI_NOW_M_1_BELOW_MIN               0
RSI_NOW_M_BELOW_AVG                 0
RSI_NOW_M_BELOW_MIN                 0
TAG                                 0
TAG.keyword                         0
WHOLE_MARKET_CURVED                 0
_index                              0
btc_24h_now                         0
btc_avg_7d_mark                     0
btc_candle_1d_closed                0
btc_candle_1h_closed                0
btc_candle_2d_closed                0
btc_candle_2h_closed                0
btc_candle_3d_closed                0
btc_candle_3h_closed                0
btc_candle_4d_closed                0
btc_candle_4h_closed                0
btc_candle_5d_closed                0
btc_candle_5h_closed                0
btc_candle_6d_closed                0
btc_candle_6h_closed                0
btc_candle_7d_closed                0
btc_candle_7h_closed                0
btc_price_difference_max_7d         0
btc_price_difference_min_7d         0
btc_price_high_hit                  0
btc_price_low_hit                   0
btc_price_max_7d                    0
btc_price_min_7d                    0
btc_price_now                       0
candle_1d.closed                    0
candle_1h.closed                    0
candle_2d.closed                    0
candle_2h.closed                    0
candle_3d.closed                    0
candle_3h.closed                    0
candle_4d.closed                    0
candle_4h.closed                    0
candle_5d.closed                    0
candle_5h.closed                    0
candle_6d.closed                    0
candle_6h.closed                    0
candle_7d.closed                    0
candle_7h.closed                    0
candle_average_8hours_low_high      0
candle_min_max_8hours_low_high      0
cmc_rank                            0
condition                           0
condition.keyword                   0
customer                            0
customer.keyword                    0
duration                            0
duration_01_lost                    0
duration_01_win                     0
duration_02_lost                    0
duration_lost_03                    0
duration_lost_04                    0
duration_lost_05                    0
eth_24h_now                         0
high_supply_vs_demand               0
macd                                0
macd_1d_percentage_difference       0
macd_1h_percentage_difference       0
macd_1min                           0
macd_1min_percentage_difference     0
macd_5min                           0
macd_5min_percentage_difference     0
macd_60min                          0
macd_btc                            0
macd_btc_sline                      0
macd_signal_line                    0
macd_signal_line_1min               0
macd_signal_line_5min               0
macd_signal_line_60min              0
macd_sline                          0
market_count_15m                    0
market_count_30m                    0
market_count_now                    0
pct.24h                             0
pct.24h_8d.avg                      0
percentage_24h                      0
percentage_difference               0
percentiles_1                       0
percentiles_1_below                 0
percentiles_25_below                0
percentiles_5                       0
percentiles_50                      0
percentiles_5_below                 0
percentiles_75                      0
percentiles_95                      0
percentiles_99                      0
performance                         0
price                               0
price_1d_ago                        0
price_7d_ago                        0
price_diff_change                   0
price_diff_change_10h               0
price_diff_change_10h_stored        0
price_diff_change_10min             0
price_diff_change_10min_1           0
price_diff_change_10min_bucket_5    0
price_diff_change_1d                0
price_diff_now_1d                   0
price_diff_now_7d                   0
price_difference_1d_ago             0
price_difference_7d_ago             0
price_exit                          0
price_now                           0
qty                                 0
result                              0
roc_9d_1min                         0
roc_9d_5min                         0
roc_9d_60min                        0
roc_9d_btc                          0
rsi                                 0
rsi_1min                            0
rsi_5min                            0
rsi_60min                           0
rsi_btc                             0
side                                0
slLimitPrice                        0
slOrderType                         0
state                               0
status                              0
status_at_001_win                   0
stopLoss                            0
symbol                              0
symbol.keyword                      0
takeProfit                          0
tendancies_pct_down                 0
tendancies_pct_up                   0
timeInForce                         0
timeInForce.keyword                 0
timestamp                           0
timestamp_updated                   0
tpLimitPrice                        0
track_candle_down_avg               0
track_candle_down_count             0
track_candle_up_avg                 0
track_candle_up_count               0
volume_90d                          0
volume_bybit_90d                    0
volume_bybit_now                    0
volume_bybit_now.keyword            0
volume_now                          0
worked                              0
zoom_17h_max_price                  0
zoom_8d_avg                         0
zoom_8d_price                       0
outcome_02                          0

Show only columns with missing values

In [216]:
missing_filtered = data.isnull().sum()
missing_filtered = missing_filtered[missing_filtered > 0]

print("Columns with missing values:")
print(missing_filtered)

Columns with missing values:
Series([], dtype: int64)

In [217]:
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,False,False,True,False,False,False,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,False,False,False,False,False,False,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,False,False,False,True,False,False,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,False,False,False,False,False,False,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,False,False,False,False,False,False,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

HANDLING BOOLEAN DATA

In [218]:
print(data['ABOVE_1H_NEGATIVE'].dtype)

bool

In [219]:
data['ABOVE_1H_NEGATIVE'].unique()

array([False])

In [220]:
data['ABOVE_1H_NEGATIVE'] = data['ABOVE_1H_NEGATIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,False,True,False,False,False,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,False,False,False,False,False,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,False,False,True,False,False,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,False,False,False,False,False,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,False,False,False,False,False,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [221]:
print(data['ABOVE_1H_POSITIVE'].dtype)

bool

In [222]:
data['ABOVE_1H_POSITIVE'].unique()

array([False])

In [223]:
data['ABOVE_1H_POSITIVE'] = data['ABOVE_1H_POSITIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,True,False,False,False,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,False,False,False,False,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,False,True,False,False,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,False,False,False,False,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,False,False,False,False,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [224]:
print(data['BELOW'].dtype)

bool

In [225]:
data['BELOW'].unique()

array([ True, False])

In [226]:

data['BELOW'] = data['BELOW'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,False,False,False,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,False,False,False,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,True,False,False,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,False,False,False,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,False,False,False,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [227]:
print(data['BELOW_1H'].dtype)

bool

In [228]:
data['BELOW_1H'].unique()

array([False,  True])

In [229]:
data['BELOW_1H'] = data['BELOW_1H'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,False,False,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,False,False,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,False,False,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,False,False,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,False,False,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [230]:
print(data['BELOW_1H_BIG'].dtype)

bool

In [231]:
data['BELOW_1H_BIG'].unique()

array([False,  True])

In [232]:
data['BELOW_1H_BIG'] = data['BELOW_1H_BIG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,False,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,False,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,False,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,False,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,False,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [233]:
print(data['BELOW_1H_GO'].dtype)

bool

In [234]:
data['BELOW_1H_GO'].unique()

array([False,  True])

In [235]:
data['BELOW_1H_GO'] = data['BELOW_1H_GO'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,False,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,False,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,True,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,False,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,False,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [236]:
print(data['BELOW_1H_STAMP'].dtype)

bool

In [237]:
data['BELOW_1H_STAMP'].unique()

array([False,  True])

In [238]:
data['BELOW_1H_STAMP'] = data['BELOW_1H_STAMP'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,False,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,False,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,False,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,False,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,False,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [239]:
print(data['BUY_H'].dtype)

bool

In [240]:
data['BUY_H'].unique()

array([False,  True])

In [241]:
data['BUY_H'] = data['BUY_H'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,False,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,False,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,False,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,False,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,False,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [242]:
print(data['EXTREME_ABOVE'].dtype)

bool

In [243]:
data['EXTREME_ABOVE'].unique()

array([False,  True])

In [244]:
data['EXTREME_ABOVE'] = data['EXTREME_ABOVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,False,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,False,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,False,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,False,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,False,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [245]:
print(data['EXTREME_BELOW'].dtype)

bool

In [246]:
data['EXTREME_BELOW'].unique()

array([False])

In [247]:
data['EXTREME_BELOW'] = data['EXTREME_BELOW'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [248]:
print(data['FAILED_PURCHASED'].dtype)

bool

In [249]:
data['FAILED_PURCHASED'].unique()

array([False])

In [250]:
data['FAILED_PURCHASED'] = data['FAILED_PURCHASED'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [251]:
print(data['INDICATOR_1'].dtype)

bool

In [252]:
data['INDICATOR_1'].unique()

array([False,  True])

In [253]:
data['INDICATOR_1'] = data['INDICATOR_1'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [254]:
print(data['INDICATOR_10'].dtype)

bool

In [255]:
data['INDICATOR_10'].unique()

array([ True, False])

In [256]:
data['INDICATOR_10'] = data['INDICATOR_10'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [257]:
print(data['INDICATOR_11'].dtype)

bool

In [258]:
data['INDICATOR_11'].unique()

array([ True, False])

In [259]:
data['INDICATOR_11'] = data['INDICATOR_11'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [260]:
print(data['INDICATOR_2'].dtype)

bool

In [261]:
data['INDICATOR_2'].unique()

array([False])

In [262]:
data['INDICATOR_2'] = data['INDICATOR_2'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [263]:
print(data['INDICATOR_20'].dtype)

bool

In [264]:
data['INDICATOR_20'].unique()

array([False,  True])

In [265]:
data['INDICATOR_20'] = data['INDICATOR_20'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [266]:
print(data['INDICATOR_21'].dtype)

bool

In [267]:
data['INDICATOR_21'].unique()

array([False,  True])

In [268]:
data['INDICATOR_21'] = data['INDICATOR_21'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [269]:
print(data['INDICATOR_22'].dtype)

bool

In [270]:
data['INDICATOR_22'].unique()

array([False,  True])

In [271]:
data['INDICATOR_22'] = data['INDICATOR_22'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [272]:
print(data['INDICATOR_23'].dtype)

bool

In [273]:
data['INDICATOR_23'].unique()

array([False,  True])

In [274]:
data['INDICATOR_23'] = data['INDICATOR_23'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [275]:
print(data['INDICATOR_24'].dtype)

bool

In [276]:
data['INDICATOR_24'].unique()

array([ True, False])

In [277]:
data['INDICATOR_24'] = data['INDICATOR_24'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [278]:
print(data['INDICATOR_3'].dtype)

bool

In [279]:
data['INDICATOR_3'].unique()

array([False,  True])

In [280]:
data['INDICATOR_3'] = data['INDICATOR_3'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [281]:
print(data['INDICATOR_4'].dtype)

bool

In [282]:
data['INDICATOR_4'].unique()

array([ True, False])

In [283]:
data['INDICATOR_4'] = data['INDICATOR_4'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [284]:
print(data['INDICATOR_5'].dtype)

bool

In [285]:
data['INDICATOR_5'].unique()

array([False,  True])

In [286]:
data['INDICATOR_5'] = data['INDICATOR_5'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [287]:
print(data['INDICATOR_6'].dtype)

bool

In [288]:
data['INDICATOR_6'].unique()

array([ True, False])

In [289]:
data['INDICATOR_6'] = data['INDICATOR_6'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [290]:
print(data['INDICATOR_7'].dtype)

bool

In [291]:
data['INDICATOR_7'].unique()

array([False,  True])

In [292]:
data['INDICATOR_7'] = data['INDICATOR_7'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [293]:
print(data['INDICATOR_8'].dtype)

bool

In [294]:
data['INDICATOR_8'].unique()

array([False,  True])

In [295]:
data['INDICATOR_8'] = data['INDICATOR_8'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [296]:
print(data['INDICATOR_9'].dtype)

bool

In [297]:
data['INDICATOR_9'].unique()

array([False,  True])

In [298]:
data['INDICATOR_9'] = data['INDICATOR_9'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [299]:
print(data['JUST_CROSS_ABOVE'].dtype)

bool

In [300]:
data['JUST_CROSS_ABOVE'].unique()

array([False,  True])

In [301]:
data['JUST_CROSS_ABOVE'] = data['JUST_CROSS_ABOVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [302]:
print(data['MACD_1H_BELOW_AVG'].dtype)

bool

In [303]:
data['MACD_1H_BELOW_AVG'].unique()

array([False])

In [304]:
data['MACD_1H_BELOW_AVG'] = data['MACD_1H_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [305]:
print(data['MACD_1H_BELOW_MIN'].dtype)

bool

In [306]:
data['MACD_1H_BELOW_MIN'].unique()

array([False])

In [307]:
data['MACD_1H_BELOW_MIN'] = data['MACD_1H_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [308]:
print(data['MACD_1H_UP'].dtype)

bool

In [309]:
data['MACD_1H_UP'].unique()

array([False,  True])

In [310]:
data['MACD_1H_UP'] = data['MACD_1H_UP'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [311]:
print(data['MACD_DAY_CURVED'].dtype)

bool

In [312]:
data['MACD_DAY_CURVED'].unique()

array([False])

In [313]:
data['MACD_DAY_CURVED'] = data['MACD_DAY_CURVED'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [314]:
print(data['MACD_DAY_MIXED'].dtype)

bool

In [315]:
data['MACD_DAY_MIXED'].unique()

array([False])

In [316]:
data['MACD_DAY_MIXED'] = data['MACD_DAY_MIXED'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [317]:
print(data['MACD_DAY_NEGATIVE'].dtype)

bool

In [318]:
data['MACD_DAY_NEGATIVE'].unique()

array([False,  True])

In [319]:
data['MACD_DAY_NEGATIVE'] = data['MACD_DAY_NEGATIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [320]:
print(data['MACD_DAY_NEGATIVE_EXTREME'].dtype)

bool

In [321]:
data['MACD_DAY_NEGATIVE_EXTREME'].unique()

array([False,  True])

In [322]:
data['MACD_DAY_NEGATIVE_EXTREME'] = data['MACD_DAY_NEGATIVE_EXTREME'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [323]:
print(data['MACD_DAY_POSITIVE'].dtype)

bool

In [324]:
data['MACD_DAY_POSITIVE'].unique()

array([False,  True])

In [325]:
data['MACD_DAY_POSITIVE'] = data['MACD_DAY_POSITIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [326]:
print(data['MACD_DAY_POSITIVE_BY_2'].dtype)

bool

In [327]:
data['MACD_DAY_POSITIVE_BY_2'].unique()

array([False,  True])

In [328]:
data['MACD_DAY_POSITIVE_BY_2'] = data['MACD_DAY_POSITIVE_BY_2'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [329]:
print(data['MACD_DAY_POSITIVE_EXTREME'].dtype)

bool

In [330]:
data['MACD_DAY_POSITIVE_EXTREME'].unique()

array([ True, False])

In [331]:
data['MACD_DAY_POSITIVE_EXTREME'] = data['MACD_DAY_POSITIVE_EXTREME'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [332]:
print(data['MACD_M_1_BELOW_AVG'].dtype)

bool

In [333]:
data['MACD_M_1_BELOW_AVG'].unique()

array([False])

In [334]:
data['MACD_M_1_BELOW_AVG'] = data['MACD_M_1_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [335]:
print(data['MACD_M_1_BELOW_MIN'].dtype)

bool

In [336]:
data['MACD_M_1_BELOW_MIN'].unique()

array([False])

In [337]:
data['MACD_M_1_BELOW_MIN'] = data['MACD_M_1_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [338]:
print(data['MACD_M_5_BELOW_AVG'].dtype)

bool

In [339]:
data['MACD_M_5_BELOW_AVG'].unique()

array([False])

In [340]:
data['MACD_M_5_BELOW_AVG'] = data['MACD_M_5_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [341]:
print(data['MACD_M_5_BELOW_MIN'].dtype)

bool

In [342]:
data['MACD_M_5_BELOW_MIN'].unique()

array([False])

In [343]:
data['MACD_M_5_BELOW_MIN'] = data['MACD_M_5_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [344]:
print(data['ROC_9D_H_BELOW_AVG'].dtype)

bool

In [345]:
data['ROC_9D_H_BELOW_AVG'].unique()

array([False])

In [346]:
data['ROC_9D_H_BELOW_AVG'] = data['ROC_9D_H_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [347]:
print(data['ROC_9D_H_BELOW_MIN'].dtype)

bool

In [348]:
data['ROC_9D_H_BELOW_MIN'].unique()

array([False])

In [349]:
data['ROC_9D_H_BELOW_MIN'] = data['ROC_9D_H_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [350]:
print(data['ROC_9D_M_1_BELOW_AVG'].dtype)

bool

In [351]:
data['ROC_9D_M_1_BELOW_AVG'].unique()

array([False])

In [352]:
data['ROC_9D_M_1_BELOW_AVG'] = data['ROC_9D_M_1_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [353]:
print(data['ROC_9D_M_1_BELOW_MIN'].dtype)

bool

In [354]:
data['ROC_9D_M_1_BELOW_MIN'].unique()

array([False])

In [355]:
data['ROC_9D_M_1_BELOW_MIN'] = data['ROC_9D_M_1_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [356]:
print(data['ROC_9D_M_BELOW_AVG'].dtype)

bool

In [357]:
data['ROC_9D_M_BELOW_AVG'].unique()

array([False])

In [358]:
data['ROC_9D_M_BELOW_AVG'] = data['ROC_9D_M_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [359]:
print(data['ROC_9D_M_BELOW_MIN'].dtype)

bool

In [360]:
data['ROC_9D_M_BELOW_MIN'].unique()

array([False])

In [361]:
data['ROC_9D_M_BELOW_MIN'] = data['ROC_9D_M_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [362]:
print(data['ROC_CURVED'].dtype)

bool

In [363]:
data['ROC_CURVED'].unique()

array([ True, False])

In [364]:
data['ROC_CURVED'] = data['ROC_CURVED'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [365]:
print(data['ROC_CURVED_DAY'].dtype)

bool

In [366]:
data['ROC_CURVED_DAY'].unique()

array([False])

In [367]:
data['ROC_CURVED_DAY'] = data['ROC_CURVED_DAY'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [368]:
print(data['ROC_CURVED_DAY_NEGATIVE'].dtype)

bool

In [369]:
data['ROC_CURVED_DAY_NEGATIVE'].unique()

array([False,  True])

In [370]:
data['ROC_CURVED_DAY_NEGATIVE'] = data['ROC_CURVED_DAY_NEGATIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [371]:
print(data['ROC_CURVED_DAY_POSITIVE'].dtype)

bool

In [372]:
data['ROC_CURVED_DAY_POSITIVE'].unique()

array([False,  True])

In [373]:
data['ROC_CURVED_DAY_POSITIVE'] = data['ROC_CURVED_DAY_POSITIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [374]:
print(data['ROC_CURVED_HOUR_NEGATIVE'].dtype)

bool

In [375]:
data['ROC_CURVED_HOUR_NEGATIVE'].unique()

array([False,  True])

In [376]:
data['ROC_CURVED_HOUR_NEGATIVE'] = data['ROC_CURVED_HOUR_NEGATIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [377]:
print(data['ROC_CURVED_HOUR_POSITIVE'].dtype)

bool

In [378]:
data['ROC_CURVED_HOUR_POSITIVE'].unique()

array([False,  True])

In [379]:
data['ROC_CURVED_HOUR_POSITIVE'] = data['ROC_CURVED_HOUR_POSITIVE'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [380]:
print(data['ROC_CURVED_NOW'].dtype)

bool

In [381]:
data['ROC_CURVED_NOW'].unique()

array([False,  True])

In [382]:
data['ROC_CURVED_NOW'] = data['ROC_CURVED_NOW'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [383]:
print(data['ROC_H'].dtype)

bool

In [384]:
data['ROC_H'].unique()

array([False,  True])

In [385]:
data['ROC_H'] = data['ROC_H'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [386]:
print(data['RSI_CURVED'].dtype)

bool

In [387]:
data['RSI_CURVED'].unique()

array([False])

In [388]:
data['RSI_CURVED'] = data['RSI_CURVED'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [389]:
print(data['RSI_CURVED_H'].dtype)

bool

In [390]:
data['RSI_CURVED_H'].unique()

array([ True, False])

In [391]:
data['RSI_CURVED_H'] = data['RSI_CURVED_H'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [392]:
print(data['RSI_DOWN'].dtype)

bool

In [393]:
data['RSI_DOWN'].unique()

array([False])

In [394]:
data['RSI_DOWN'] = data['RSI_DOWN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [395]:
print(data['RSI_DOWN_H'].dtype)

bool

In [396]:
data['RSI_DOWN_H'].unique()

array([ True, False])

In [397]:
data['RSI_DOWN_H'] = data['RSI_DOWN_H'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [398]:
print(data['RSI_H'].dtype)

bool

In [399]:
data['RSI_H'].unique()

array([ True, False])

In [400]:
data['RSI_H'] = data['RSI_H'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [401]:
print(data['RSI_NOW_H_BELOW_AVG'].dtype)

bool

In [402]:
data['RSI_NOW_H_BELOW_AVG'].unique()

array([False])

In [403]:
data['RSI_NOW_H_BELOW_AVG'] = data['RSI_NOW_H_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [404]:
print(data['RSI_NOW_H_BELOW_MIN'].dtype)

bool

In [405]:
data['RSI_NOW_H_BELOW_MIN'].unique()

array([False])

In [406]:
data['RSI_NOW_H_BELOW_MIN'] = data['RSI_NOW_H_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [407]:
print(data['RSI_NOW_M_1_BELOW_AVG'].dtype)

bool

In [408]:
data['RSI_NOW_M_1_BELOW_AVG'].unique()

array([False])

In [409]:
data['RSI_NOW_M_1_BELOW_AVG'] = data['RSI_NOW_M_1_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [410]:
print(data['RSI_NOW_M_1_BELOW_MIN'].dtype)

bool

In [411]:
data['RSI_NOW_M_1_BELOW_MIN'].unique()

array([False])

In [412]:
data['RSI_NOW_M_1_BELOW_MIN'] = data['RSI_NOW_M_1_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [413]:
print(data['RSI_NOW_M_BELOW_AVG'].dtype)

bool

In [414]:
data['RSI_NOW_M_BELOW_AVG'].unique()

array([False])

In [415]:
data['RSI_NOW_M_BELOW_AVG'] = data['RSI_NOW_M_BELOW_AVG'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [416]:
print(data['RSI_NOW_M_BELOW_MIN'].dtype)

bool

In [417]:
data['RSI_NOW_M_BELOW_MIN'].unique()

array([False])

In [418]:
data['RSI_NOW_M_BELOW_MIN'] = data['RSI_NOW_M_BELOW_MIN'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win

In [419]:
print(data['WHOLE_MARKET_CURVED'].dtype)

bool

In [420]:
data['WHOLE_MARKET_CURVED'].unique()

array([ True, False])

In [421]:
data['WHOLE_MARKET_CURVED'] = data['WHOLE_MARKET_CURVED'].astype(int)
data.head()

,ABOVE_1H_NEGATIVE,ABOVE_1H_POSITIVE,BELOW,BELOW_1H,BELOW_1H_BIG,BELOW_1H_GO,BELOW_1H_STAMP,BUY_H,EXTREME_ABOVE,EXTREME_BELOW,...,volume_90d,volume_bybit_90d,volume_bybit_now,volume_bybit_now.keyword,volume_now,worked,zoom_17h_max_price,zoom_8d_avg,zoom_8d_price,outcome_02
0,0,0,1,0,0,0,0,0,0,0,...,"316,692,220","54,407,900",7.337493e+07,7.337493e+07,"491,975,460",1.152,6.984,0.004,7.141,win
1,0,0,0,0,0,0,0,0,0,0,...,"211,683,310","65,466,110",8.345393e+07,8.345393e+07,"224,444,220",0.746,0.328,0.012,0.33,win
2,0,0,0,1,0,0,1,0,0,0,...,"16,076,887","701,815.06",2.434923e+05,2.434923e+05,"8,891,486",0.028,0.017,-0.004,0.018,win
3,0,0,0,0,0,0,0,0,0,0,...,"75,266,690","4,383,750.50",2.557151e+06,2.557151e+06,"77,816,510",0.593,41.97,0.001,38.873,win
4,0,0,0,0,0,0,0,0,0,0,...,"75,268,620","4,384,075",2.707803e+06,2.707803e+06,"77,864,680",0.594,41.97,0.001,38.873,win