UCI Bank Marketing Dataset

In [274]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import matplotlib.pyplot as plt

In [275]:
data=pd.read_csv(r"C:\Users\DELL\Downloads\bank.csv")

data.head()

,age,Job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,1,0,unknown,no
1,33,services,married,tertiary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

Checking missing data

In [276]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   Job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcoume  4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [277]:
dataset = data.isna().sum()
print("Missing Values in Each Column:\n", dataset)

Missing Values in Each Column:
 age          0
Job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcoume    0
y            0
dtype: int64

In [278]:
data.dropna(inplace=True)

In [279]:
print("Missing Values After Dropping:\n", data.isna().sum())

Missing Values After Dropping:
 age          0
Job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcoume    0
y            0
dtype: int64

In [280]:
print("Final Dataset Shape:", data.shape)
print(data.head())

Final Dataset Shape: (4521, 17)
   age          Job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no
1   33     services  married   tertiary      no     4789     yes  yes
2   35   management   single   tertiary      no     1350     yes   no
3   30   management  married   tertiary      no     1476     yes  yes
4   59  blue-collar  married  secondary      no        0     yes   no

    contact  day month  duration  campaign  pdays  previous poutcoume   y
0  cellular   19   oct        79         1      1         0   unknown  no
1  cellular   11   may       220         1    339         4   failure  no
2  cellular   16   apr       185         1    330         1   failure  no
3   unknown    3   jun       199         4     -1         0   unknown  no
4   unknown    5   may       226         1     -1         0   unknown  no

In [281]:
data.head()

,age,Job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,1,0,unknown,no
1,33,services,married,tertiary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

Handling categorical variables

Job

In [282]:
data['Job'].unique()

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown'], dtype=object)

In [283]:
job_dummies = pd.get_dummies(data['Job'], dtype=int, drop_first = True)
job_dummies

,blue-collar,entrepreneur,housemaid,management,retired,self-employed,services,student,technician,unemployed,unknown
0,0,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4516,0,0,0,0,0,0,1,0,0,0,0
4517,0,0,0,0,0,1,0,0,0,0,0
4518,0,0,0,0,0,0,0,0,1,0,0
4519,1,0,0,0,0,0,0,0,0,0,0
4520,0,1,0,0,0,0,0,0,0,0,0

In [284]:
data = pd.concat([job_dummies, data], axis = 1)
data.head()

,blue-collar,entrepreneur,housemaid,management,retired,self-employed,services,student,technician,unemployed,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,0,0,0,0,0,0,1,...,no,cellular,19,oct,79,1,1,0,unknown,no
1,0,0,0,0,0,0,1,0,0,0,...,yes,cellular,11,may,220,1,339,4,failure,no
2,0,0,0,1,0,0,0,0,0,0,...,no,cellular,16,apr,185,1,330,1,failure,no
3,0,0,0,1,0,0,0,0,0,0,...,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,1,0,0,0,0,0,0,0,0,0,...,no,unknown,5,may,226,1,-1,0,unknown,no

In [285]:
data.drop(['Job'], axis = 1, inplace = True)
data.head()

,blue-collar,entrepreneur,housemaid,management,retired,self-employed,services,student,technician,unemployed,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,0,0,0,0,0,0,1,...,no,cellular,19,oct,79,1,1,0,unknown,no
1,0,0,0,0,0,0,1,0,0,0,...,yes,cellular,11,may,220,1,339,4,failure,no
2,0,0,0,1,0,0,0,0,0,0,...,no,cellular,16,apr,185,1,330,1,failure,no
3,0,0,0,1,0,0,0,0,0,0,...,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,1,0,0,0,0,0,0,0,0,0,...,no,unknown,5,may,226,1,-1,0,unknown,no

Marital

In [286]:
data['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [287]:
marital_dummies = pd.get_dummies(data['marital'], dtype=int, drop_first = True)
marital_dummies

      married  single
0           1       0
1           1       0
2           0       1
3           1       0
4           1       0
...       ...     ...
4516        1       0
4517        1       0
4518        1       0
4519        1       0
4520        0       1

[4521 rows x 2 columns]

In [288]:
data = pd.concat([marital_dummies, data], axis = 1)
data.head()

,married,single,blue-collar,entrepreneur,housemaid,management,retired,self-employed,services,student,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,1,0,0,0,0,0,0,0,0,0,...,no,cellular,19,oct,79,1,1,0,unknown,no
1,1,0,0,0,0,0,0,0,1,0,...,yes,cellular,11,may,220,1,339,4,failure,no
2,0,1,0,0,0,1,0,0,0,0,...,no,cellular,16,apr,185,1,330,1,failure,no
3,1,0,0,0,0,1,0,0,0,0,...,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,1,0,1,0,0,0,0,0,0,0,...,no,unknown,5,may,226,1,-1,0,unknown,no

In [289]:
data.drop(['marital'], axis = 1, inplace = True)
data.head()

,married,single,blue-collar,entrepreneur,housemaid,management,retired,self-employed,services,student,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,1,0,0,0,0,0,0,0,0,0,...,no,cellular,19,oct,79,1,1,0,unknown,no
1,1,0,0,0,0,0,0,0,1,0,...,yes,cellular,11,may,220,1,339,4,failure,no
2,0,1,0,0,0,1,0,0,0,0,...,no,cellular,16,apr,185,1,330,1,failure,no
3,1,0,0,0,0,1,0,0,0,0,...,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,1,0,1,0,0,0,0,0,0,0,...,no,unknown,5,may,226,1,-1,0,unknown,no

Education

In [290]:
data['education'].unique()

array(['primary', 'tertiary', 'secondary', 'unknown'], dtype=object)

In [291]:
education_dummies = pd.get_dummies(data['education'], dtype=int, drop_first = True)
education_dummies

      secondary  tertiary  unknown
0             0         0        0
1             0         1        0
2             0         1        0
3             0         1        0
4             1         0        0
...         ...       ...      ...
4516          1         0        0
4517          0         1        0
4518          1         0        0
4519          1         0        0
4520          0         1        0

[4521 rows x 3 columns]

In [292]:
data = pd.concat([education_dummies, data], axis = 1)
data.head()

,secondary,tertiary,unknown,married,single,blue-collar,entrepreneur,housemaid,management,retired,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,1,0,0,0,0,0,0,...,no,cellular,19,oct,79,1,1,0,unknown,no
1,0,1,0,1,0,0,0,0,0,0,...,yes,cellular,11,may,220,1,339,4,failure,no
2,0,1,0,0,1,0,0,0,1,0,...,no,cellular,16,apr,185,1,330,1,failure,no
3,0,1,0,1,0,0,0,0,1,0,...,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,1,0,0,1,0,1,0,0,0,0,...,no,unknown,5,may,226,1,-1,0,unknown,no

In [293]:
data.drop(['education'], axis = 1, inplace = True)
data.head()

,secondary,tertiary,unknown,married,single,blue-collar,entrepreneur,housemaid,management,retired,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,1,0,0,0,0,0,0,...,no,cellular,19,oct,79,1,1,0,unknown,no
1,0,1,0,1,0,0,0,0,0,0,...,yes,cellular,11,may,220,1,339,4,failure,no
2,0,1,0,0,1,0,0,0,1,0,...,no,cellular,16,apr,185,1,330,1,failure,no
3,0,1,0,1,0,0,0,0,1,0,...,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,1,0,0,1,0,1,0,0,0,0,...,no,unknown,5,may,226,1,-1,0,unknown,no

Contact

In [294]:
data['contact'].unique()

array(['cellular', 'unknown', 'telephone'], dtype=object)

In [295]:
contact_dummies = pd.get_dummies(data['contact'], dtype=int, drop_first = True)
contact_dummies

      telephone  unknown
0             0        0
1             0        0
2             0        0
3             0        1
4             0        1
...         ...      ...
4516          0        0
4517          0        1
4518          0        0
4519          0        0
4520          0        0

[4521 rows x 2 columns]

In [296]:
data = pd.concat([contact_dummies, data], axis = 1)
data.head()

,telephone,unknown,secondary,tertiary,unknown,married,single,blue-collar,entrepreneur,housemaid,...,loan,contact,day,month,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,0,0,1,0,0,0,0,...,no,cellular,19,oct,79,1,1,0,unknown,no
1,0,0,0,1,0,1,0,0,0,0,...,yes,cellular,11,may,220,1,339,4,failure,no
2,0,0,0,1,0,0,1,0,0,0,...,no,cellular,16,apr,185,1,330,1,failure,no
3,0,1,0,1,0,1,0,0,0,0,...,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,0,1,1,0,0,1,0,1,0,0,...,no,unknown,5,may,226,1,-1,0,unknown,no

In [297]:
data.drop(['contact'], axis = 1, inplace = True)
data.head()

,telephone,unknown,secondary,tertiary,unknown,married,single,blue-collar,entrepreneur,housemaid,...,housing,loan,day,month,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,0,0,1,0,0,0,0,...,no,no,19,oct,79,1,1,0,unknown,no
1,0,0,0,1,0,1,0,0,0,0,...,yes,yes,11,may,220,1,339,4,failure,no
2,0,0,0,1,0,0,1,0,0,0,...,yes,no,16,apr,185,1,330,1,failure,no
3,0,1,0,1,0,1,0,0,0,0,...,yes,yes,3,jun,199,4,-1,0,unknown,no
4,0,1,1,0,0,1,0,1,0,0,...,yes,no,5,may,226,1,-1,0,unknown,no

Month

In [298]:
data['month'].unique()

array(['oct', 'may', 'apr', 'jun', 'feb', 'aug', 'jan', 'jul', 'nov',
       'sep', 'mar', 'dec'], dtype=object)

In [299]:
month_dummies = pd.get_dummies(data['month'], dtype=int, drop_first = True)
month_dummies

      aug  dec  feb  jan  jul  jun  mar  may  nov  oct  sep
0       0    0    0    0    0    0    0    0    0    1    0
1       0    0    0    0    0    0    0    1    0    0    0
2       0    0    0    0    0    0    0    0    0    0    0
3       0    0    0    0    0    1    0    0    0    0    0
4       0    0    0    0    0    0    0    1    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
4516    0    0    0    0    1    0    0    0    0    0    0
4517    0    0    0    0    0    0    0    1    0    0    0
4518    1    0    0    0    0    0    0    0    0    0    0
4519    0    0    1    0    0    0    0    0    0    0    0
4520    0    0    0    0    0    0    0    0    0    0    0

[4521 rows x 11 columns]

In [300]:
data = pd.concat([month_dummies, data], axis = 1)
data.head()

,aug,dec,feb,jan,jul,jun,mar,may,nov,oct,...,housing,loan,day,month,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,0,0,0,0,0,0,1,...,no,no,19,oct,79,1,1,0,unknown,no
1,0,0,0,0,0,0,0,1,0,0,...,yes,yes,11,may,220,1,339,4,failure,no
2,0,0,0,0,0,0,0,0,0,0,...,yes,no,16,apr,185,1,330,1,failure,no
3,0,0,0,0,0,1,0,0,0,0,...,yes,yes,3,jun,199,4,-1,0,unknown,no
4,0,0,0,0,0,0,0,1,0,0,...,yes,no,5,may,226,1,-1,0,unknown,no

In [301]:
data.drop(['month'], axis = 1, inplace = True)
data.head()

,aug,dec,feb,jan,jul,jun,mar,may,nov,oct,...,balance,housing,loan,day,duration,campaign,pdays,previous,poutcoume,y
0,0,0,0,0,0,0,0,0,0,1,...,1787,no,no,19,79,1,1,0,unknown,no
1,0,0,0,0,0,0,0,1,0,0,...,4789,yes,yes,11,220,1,339,4,failure,no
2,0,0,0,0,0,0,0,0,0,0,...,1350,yes,no,16,185,1,330,1,failure,no
3,0,0,0,0,0,1,0,0,0,0,...,1476,yes,yes,3,199,4,-1,0,unknown,no
4,0,0,0,0,0,0,0,1,0,0,...,0,yes,no,5,226,1,-1,0,unknown,no

Poutcome

In [302]:
data['poutcoume'].unique()

array(['unknown', 'failure', 'other', 'success'], dtype=object)

In [303]:
poutcome_dummies = pd.get_dummies(data['poutcoume'], dtype=int, drop_first = True)
poutcome_dummies

      other  success  unknown
0         0        0        1
1         0        0        0
2         0        0        0
3         0        0        1
4         0        0        1
...     ...      ...      ...
4516      0        0        1
4517      0        0        1
4518      0        0        1
4519      1        0        0
4520      1        0        0

[4521 rows x 3 columns]

In [304]:
data = pd.concat([poutcome_dummies, data], axis = 1)
data.head()

,other,success,unknown,aug,dec,feb,jan,jul,jun,mar,...,balance,housing,loan,day,duration,campaign,pdays,previous,poutcoume,y
0,0,0,1,0,0,0,0,0,0,0,...,1787,no,no,19,79,1,1,0,unknown,no
1,0,0,0,0,0,0,0,0,0,0,...,4789,yes,yes,11,220,1,339,4,failure,no
2,0,0,0,0,0,0,0,0,0,0,...,1350,yes,no,16,185,1,330,1,failure,no
3,0,0,1,0,0,0,0,0,1,0,...,1476,yes,yes,3,199,4,-1,0,unknown,no
4,0,0,1,0,0,0,0,0,0,0,...,0,yes,no,5,226,1,-1,0,unknown,no

In [305]:
data.drop(['poutcoume'], axis = 1, inplace = True)
data.head()

,other,success,unknown,aug,dec,feb,jan,jul,jun,mar,...,default,balance,housing,loan,day,duration,campaign,pdays,previous,y
0,0,0,1,0,0,0,0,0,0,0,...,no,1787,no,no,19,79,1,1,0,no
1,0,0,0,0,0,0,0,0,0,0,...,no,4789,yes,yes,11,220,1,339,4,no
2,0,0,0,0,0,0,0,0,0,0,...,no,1350,yes,no,16,185,1,330,1,no
3,0,0,1,0,0,0,0,0,1,0,...,no,1476,yes,yes,3,199,4,-1,0,no
4,0,0,1,0,0,0,0,0,0,0,...,no,0,yes,no,5,226,1,-1,0,no

Default

In [306]:
data['default'].unique()

array(['no', 'yes'], dtype=object)

In [307]:
data['default'] = data['default'].apply(lambda x: 0 if x == 'no' else 1)
data.head()

,other,success,unknown,aug,dec,feb,jan,jul,jun,mar,...,default,balance,housing,loan,day,duration,campaign,pdays,previous,y
0,0,0,1,0,0,0,0,0,0,0,...,0,1787,no,no,19,79,1,1,0,no
1,0,0,0,0,0,0,0,0,0,0,...,0,4789,yes,yes,11,220,1,339,4,no
2,0,0,0,0,0,0,0,0,0,0,...,0,1350,yes,no,16,185,1,330,1,no
3,0,0,1,0,0,0,0,0,1,0,...,0,1476,yes,yes,3,199,4,-1,0,no
4,0,0,1,0,0,0,0,0,0,0,...,0,0,yes,no,5,226,1,-1,0,no

Housing

In [308]:
data['housing'].unique()

array(['no', 'yes'], dtype=object)

In [309]:
data['housing'] = data['housing'].apply(lambda x: 0 if x == 'no' else 1)
data.head()

,other,success,unknown,aug,dec,feb,jan,jul,jun,mar,...,default,balance,housing,loan,day,duration,campaign,pdays,previous,y
0,0,0,1,0,0,0,0,0,0,0,...,0,1787,0,no,19,79,1,1,0,no
1,0,0,0,0,0,0,0,0,0,0,...,0,4789,1,yes,11,220,1,339,4,no
2,0,0,0,0,0,0,0,0,0,0,...,0,1350,1,no,16,185,1,330,1,no
3,0,0,1,0,0,0,0,0,1,0,...,0,1476,1,yes,3,199,4,-1,0,no
4,0,0,1,0,0,0,0,0,0,0,...,0,0,1,no,5,226,1,-1,0,no

In [310]:
data['loan'].unique()

array(['no', 'yes'], dtype=object)

In [311]:
data['loan'] = data['loan'].apply(lambda x: 0 if x == 'no' else 1)
data.head()

,other,success,unknown,aug,dec,feb,jan,jul,jun,mar,...,default,balance,housing,loan,day,duration,campaign,pdays,previous,y
0,0,0,1,0,0,0,0,0,0,0,...,0,1787,0,0,19,79,1,1,0,no
1,0,0,0,0,0,0,0,0,0,0,...,0,4789,1,1,11,220,1,339,4,no
2,0,0,0,0,0,0,0,0,0,0,...,0,1350,1,0,16,185,1,330,1,no
3,0,0,1,0,0,0,0,0,1,0,...,0,1476,1,1,3,199,4,-1,0,no
4,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,5,226,1,-1,0,no

Y

In [312]:
data['y'].unique()

array(['no', 'yes'], dtype=object)

In [313]:
data['y'] = data['y'].apply(lambda x: 0 if x == 'no' else 1)
data.head()

,other,success,unknown,aug,dec,feb,jan,jul,jun,mar,...,default,balance,housing,loan,day,duration,campaign,pdays,previous,y
0,0,0,1,0,0,0,0,0,0,0,...,0,1787,0,0,19,79,1,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,4789,1,1,11,220,1,339,4,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1350,1,0,16,185,1,330,1,0
3,0,0,1,0,0,0,0,0,1,0,...,0,1476,1,1,3,199,4,-1,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,5,226,1,-1,0,0

Creating the Training Set and the Test Set

In [314]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

Getting the Training Set and the Test Set

In [315]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)

X_train Shape: (3616, 42)
X_test Shape: (905, 42)

Building and training the model

In [316]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

Training the model

In [317]:
model.fit(X_train, y_train)

RandomForestClassifier()

Inference

In [318]:
y_pred = model.predict(X_test)

Evaluating the model

Making the Confusion Matrix

In [319]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[781,  12],
       [ 80,  32]], dtype=int64)

In [320]:
result = (777+32) / (777+16+80+32) 
print("Accuracy:", result)

Accuracy: 0.8939226519337017

Accuracy

In [321]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8983425414364641